root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o main ."
bin = "main"
full_bin = "./main"
exclude_dir = ["tmp", "vendor"]
include_ext = ["go", "tpl", "tmpl", "html"]

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"

[log]
time = false
